{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "elasticsearch-query-exporter-queries.fullname" . }}
  labels:
    {{- include "elasticsearch-query-exporter-queries.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- toYaml .Values.serviceSelectorLabels | nindent 6 }}
  endpoints:
    {{- range .Values.queries }}
    - port: http
      path: /probe
      interval: {{ .interval | default $.Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .scrapeTimeout | default $.Values.serviceMonitor.scrapeTimeout }}
      params:
        index-pattern:
          - {{ .indexPattern | quote }}
        search-string:
          - {{ .searchString | quote }}
        {{- if .patternType }}
        pattern_type:
          - {{ .patternType | quote }}
        {{- end }}
        {{- if .field }}
        field:
          - {{ .field | quote }}
        {{- end }}
        {{- if .timeField }}
        time-field:
          - {{ .timeField | quote }}
        {{- end }}
        {{- if .metricName }}
        metric_name:
          - {{ .metricName | quote }}
        {{- end }}
        {{- if .queryId }}
        query_id:
          - {{ .queryId | quote }}
        {{- end }}
        label_field_map:
          {{- range $label, $field := .labelFieldMap }}
          - {{ printf "%s=%s" $label $field | quote }}
          {{- end }}
      {{- with .metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
{{- end }}
